"""
Solve the coupling encoding on a given environment and export the optimal plan
as Flatland action/3 facts for the flatlands_visualisation framework.

Run from flatlands/src:
    python export_actions.py                          # default: connect_environment.lp
    python export_actions.py my_env.lp                # name derived from the file
    python export_actions.py my_env.lp myname         # explicit output name
    python export_actions.py my_env.lp myname --max-wait 3

Writes  <VIS>/asp/<name>_actions.lp , the static action file that solve.py loads
via asp/params.py (set primary=['asp/<name>_actions.lp']).
"""
import os
import argparse
import clingo

# the logic encodings are shared across all environments
ENCODINGS = ["encoding_connect.lp", "tracks.lp", "to_actions.lp"]
VIS_ASP = "/Users/marvin/repos/flatlands_visualisation/flatland/asp"


def derive_name(env_file):
    """connect_environment.lp -> connect ; my_env.lp -> my_env"""
    stem = os.path.splitext(os.path.basename(env_file))[0]
    return stem[:-len("_environment")] if stem.endswith("_environment") else stem


def get_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("env", nargs="?", default="connect_environment.lp",
                   help="environment .lp file (default: connect_environment.lp)")
    p.add_argument("name", nargs="?", default=None,
                   help="output name; defaults to the env filename stem")
    p.add_argument("--max-wait", type=int, default=None,
                   help="override the max_wait constant in the encoding")
    return p.parse_args()


def main():
    args = get_args()
    name = args.name or derive_name(args.env)
    out = os.path.join(VIS_ASP, f"{name}_actions.lp")

    ctl_args = []
    if args.max_wait is not None:
        ctl_args = ["-c", f"max_wait={args.max_wait}"]
    ctl = clingo.Control(ctl_args)

    for f in ENCODINGS + [args.env]:
        ctl.load(f)
    ctl.ground([("base", [])])

    best = None
    with ctl.solve(yield_=True) as handle:
        for model in handle:
            best = model.symbols(shown=True)  # keep last -> optimal under #minimize

    if best is None:
        raise SystemExit("UNSAT - no plan found")

    acts = []
    for a in best:
        if a.name == "action":
            tid = a.arguments[0].arguments[0].number
            act = a.arguments[1].name
            time = a.arguments[2].number
            acts.append((time, tid, act))
    acts.sort()

    with open(out, "w") as fh:
        fh.write(f"% auto-generated by export_actions.py from {args.env}\n")
        cur = None
        for time, tid, act in acts:
            if time != cur:
                fh.write(f"\n% t={time}\n")
                cur = time
            fh.write(f"action(train({tid}),{act},{time}).\n")
        fh.write("\n#show action/3.\n")

    print(f"wrote {len(acts)} action atoms -> {out}")
    print(f"now set asp/params.py:  primary=['asp/{name}_actions.lp']")


if __name__ == "__main__":
    main()
